apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "web-project.namespace" . }}
  name: {{ include "web-project.fullname" . }}
  labels:
    {{- include "web-project.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.appPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "web-project.selectorLabels" . | nindent 4 }}
