{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ include "web-project.namespace" . }}
  name: {{ include "web-project.serviceAccountName" . }}
  labels:
{{ include "web-project.labels" . | nindent 4 }}
{{- end -}}
