server:
  port: 80
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ticketsystem?useUnicode=true&;characterEncoding=UTF-8&useSSL=false
    username: root
    password: kiss4400
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  devtools:
    restart:
      enabled: false
  session:
    #HTTPSession存储方式（none 内存存储）
    store-type: none
  resources:
    #静态资源文件路径
    static-locations: classpath:/static/
logging:
  file: ./log.log
  level:
      com.dragon.study.spring.boot: DEBUG
mybatis:
  #mybatis xml配置路径
  mapper-locations: classpath:com/nix/mapping/*.xml
  type-aliases-package: com.nix.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl