apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.16.4
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers
controlPlaneEndpoint: "cswx-k8s-master1:6443"
controllerManager: {}
networking:
  serviceSubnet: "10.96.0.0/16"
  podSubnet: "10.100.0.1/20"
  dnsDomain: "cluster.local"
  scheduler: {}

---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
featureGates:
  SupportIPVSProxyMode: true
mode: ipvs
