---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eip-nfs-middleware
  name: eip-nfs-middleware
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eip-nfs-middleware
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eip-nfs-middleware
    spec:
      containers:
        - env:
            - name: PROVISIONER_NAME
              value: nfs-docker
            - name: NFS_SERVER
              value: 3fafc4b237-hhd94.cn-shanghai.nas.aliyuncs.com
            - name: NFS_PATH
              value: /middleware
          image: 'quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11'
          name: nfs-client-provisioner
          volumeMounts:
            - mountPath: /persistentvolumes
              name: nfs-client-root
      serviceAccountName: eip-nfs-client-provisioner
      volumes:
        - name: nfs-client-root
          nfs:
            path: /middleware
            server: 3fafc4b237-hhd94.cn-shanghai.nas.aliyuncs.com

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    k8s.eip.work/storageNamespace: middleware
    k8s.eip.work/storageType: nfs_client_provisioner
  name: middleware
mountOptions:
  - 'nolock,tcp,noresvport'
  - vers=3
parameters:
  archiveOnDelete: 'false'
provisioner: nfs-middleware
reclaimPolicy: Retain
volumeBindingMode: Immediate

